#!/usr/bin/env bash
#
# Sourdough — DreamHost shared-hosting setup (run ON THE SERVER).
#
#   cd ~/sourdough.vaportrash.net
#   git pull
#   bash deploy/dreamhost-setup.sh
#
# DreamHost shared hosting blocks V8's JIT (writable+executable memory), so a
# plain `node` crashes at startup. This script runs Node with --jitless
# everywhere — for the build AND for the Passenger runtime (via a wrapper) — and
# wires up the Passenger config. Re-running it is safe (idempotent).

set -euo pipefail

DOMAIN="sourdough.vaportrash.net"

step() { printf "\n\033[1;34m==>\033[0m %s\n" "$1"; }
ok()   { printf "\033[1;32m  \xe2\x9c\x93\033[0m %s\n" "$1"; }
warn() { printf "\033[1;33m  !\033[0m %s\n" "$1"; }
die()  { printf "\033[1;31m  \xe2\x9c\x97 %s\033[0m\n" "$1" >&2; exit 1; }

# 0. Must run from the app root.
if [ ! -f package.json ] || [ ! -f app.js ]; then
  die "Run this from the app root (the folder containing package.json and app.js)."
fi

# 1. Load nvm + find Node.
step "Locating Node (need >= 22.5 for node:sqlite)"
# shellcheck disable=SC1090
[ -s "$HOME/.nvm/nvm.sh" ] && . "$HOME/.nvm/nvm.sh" >/dev/null 2>&1 || true
nvm use default >/dev/null 2>&1 || true
NODE_BIN="$(command -v node || true)"
[ -n "$NODE_BIN" ] || die "node not found. Install it: nvm install 24 && nvm alias default 24"
ok "node binary: $NODE_BIN"

# 2. Confirm --jitless boots and node:sqlite is usable on this version.
step "Verifying --jitless works and node:sqlite is available"
"$NODE_BIN" --jitless -e "require('node:sqlite'); console.log('node:sqlite ok on Node ' + process.versions.node)" \
  || die "node --jitless can't load node:sqlite. You need Node >= 22.5 (nvm install 24 && nvm alias default 24)."
ok "jitless + node:sqlite confirmed"

# 3. Wrapper so Passenger always launches Node with --jitless.
step "Installing ~/bin/node-jitless wrapper"
mkdir -p "$HOME/bin"
cat > "$HOME/bin/node-jitless" <<EOF
#!/bin/bash
exec "$NODE_BIN" --jitless "\$@"
EOF
chmod +x "$HOME/bin/node-jitless"
ok "wrapper -> $HOME/bin/node-jitless"

# 4. Install deps + build, forcing --jitless on every child Node process.
export NODE_OPTIONS="--jitless"
step "Installing dependencies (npm ci)"
npm ci
ok "dependencies installed"

step "Building (npm run build) — this is the slow part"
npm run build
ok "production build complete"

# 5. Passenger config in the document root.
step "Writing public/.htaccess (Passenger -> jitless Node, production)"
mkdir -p public
cat > public/.htaccess <<EOF
# Generated by deploy/dreamhost-setup.sh
PassengerNodejs $HOME/bin/node-jitless
PassengerAppEnv production
EOF
ok "public/.htaccess written"

# 6. Restart Passenger.
step "Triggering a Passenger restart"
mkdir -p tmp && touch tmp/restart.txt
ok "tmp/restart.txt touched"

# 7. The bits only you can do (panel).
cat <<EOF

------------------------------------------------------------------
 Server side is DONE. Finish these ONE-TIME steps in the DreamHost
 panel (Websites -> Manage "$DOMAIN"):

   1. Web directory  ->  $DOMAIN/public
   2. Enable Passenger (Ruby/NodeJS/Python apps enabled)
   3. Enable HTTPS (Secure Hosting / Let's Encrypt)

 Then open:  https://$DOMAIN
   - First request boots the app and creates/migrates/seeds the DB.
   - Demo login: demo@sourdough.dev / password  (change it after!)
------------------------------------------------------------------
EOF

# 8. Optional health check (only if interactive).
if [ -t 0 ]; then
  read -r -p "Done with the panel steps and want a health check now? [y/N] " yn
  if [[ "$yn" =~ ^[Yy]$ ]]; then
    step "GET https://$DOMAIN/api/apis"
    if curl -fsS "https://$DOMAIN/api/apis" | head -c 300; then
      printf "\n"; ok "It's alive."
    else
      warn "No healthy response yet. Wait a few seconds for Passenger to boot,"
      warn "double-check the web directory is set to '$DOMAIN/public', then run:"
      warn "  touch tmp/restart.txt   (and reload the page)"
    fi
  fi
fi
